#+author: multiades

* README
:PROPERTIES:
:EXPORT_FILE_NAME: ./README
:EXPORT_OPTIONS: toc:nil title:nil
:END:

A tiny Nix library of auxiliary functions with no nixpkgs dependency (self-contained).

** Lazy design

Desiring to avoid the overhead of a recursive attribute set, the library was designed to use a self-referencing attribute set so modules can call each other while remaining independently importable. Due to Nix's laziness, nothing is evaluated until actually accessed. 

The =./default.nix= file is the aggregator of the modules in the =./lib= directory.

** Usage

*** Note

Some of the functions' definitions use the experimental Nix pipe operators. Make sure you enable them beforehand.

*** Barebones import

Here is a minimal example of using the library as a standalone import:

#+begin_src nix

let 
  bibliothix = builtins.import 
    (builtins.fetchTarball {
      url = "https://github.com/multiades/bibliothix/archive/main.tar.gz";
    });
in 
  bibliothix.list.isMember 
    "foo" 
    [ 
      "foo"
      "bar"
    ]

#+end_src

The aforementioned expression should evaluate to =true=.

*** Flake usage

Flake consumers should have a =./flake.nix= file of the format:

#+begin_src nix

{
  inputs.bibliothix.url = "github:multiades/bibliothix";

  outputs = { 
    bibliothix,
    ... 
  }: {
    # Usage
  };
}

#+end_src

** Function reference list

*** List module

- listOnly
- isMember
- cons
- foldR
- foldR1
- last
- satisfies

*** Path module

- pathOnly
- withPath
- pathToBasename
- fileSearch

**** fileSearch

Useful for auto-importing all desired files in a directory without manually listing them (it even handles files with multiple types, like =./foo.tar.gz=).

It has the type signature ={ root: Path, filetype: String, suffix: String } -> List= and it locates files in a directory matching a given filetype and a filename terminating substring, returning a list of ={ basename, path }= attribute sets.

Valid filetypes (from =builtins.readDir=, since it is used):
- "regular"
- "directory"
- "symlink"
- "unknown"

Note: the function is non-recursive, it only searches the immediate contents of =root= (top-level search only).

Example usage on a directory named =./tarballs/=, containing two archives, namely =./tarballs/foo.tar.gz= and =./tarballs/bar.tar=:

#+begin_src nix

lib.path.fileSearch {
  root = ./tarballs;
  filetype = "regular";
  suffix = ".tar"; # Or even "tar"
}

#+end_src 

That should evaluate to:

#+begin_src nix

[
  { 
    basename = "foo"; 
    path = /<pathTo>/tarballs/foo.tar.gz;
  }
  { 
    basename = "bar";
    path = /<pathTo>/tarballs/bar.tar;
  }
]

#+end_src

* Documentation
:PROPERTIES:
:EXPORT_FILE_NAME: ./docs/documentation
:EXPORT_OPTIONS: title:nil
:END:
** ./flake.nix

#+begin_src nix :tangle (org-entry-get nil "ITEM")

{
  description = "Auxiliary Nix function library, no nixpkgs dependency";

  # No `inputs` attribute since no dependency is present
  
  outputs = { 
    self, 
    ...
  }: import ./default.nix;
}

#+end_src

** ./default.nix

#+begin_src nix :tangle (org-entry-get nil "ITEM")

let
  lib = {
    list = builtins.import ./lib/list.nix lib;
    path = builtins.import ./lib/path.nix lib;
  };
in
  lib

#+end_src

** ./lib/

This directory contains the modules of the library.

*** ./lib/list.nix

#+begin_src nix :tangle (org-entry-get nil "ITEM")

lib: {
  listOnly = emptyAllowed: arg: let 
    buffer = [ # Dynamic error message, will show up in other functions which use listOnly
      "this function is used strictly on"
      (if emptyAllowed then " " else " non empty ")
      "lists"
    ];
  in 
    if 
      builtins.isList arg && (emptyAllowed || arg != [])
      then arg
      else buffer
        |> builtins.concatStringsSep "" 
        |> builtins.throw;

  isMember = x: xs: builtins.any # builtins.any is a lazy, short-circuiting function, its second argument is expected to be a list
    (y: y == x)
    xs;

  satisfies = arg: predicates: builtins.any # predicates should be a list
    (predicate: predicate arg)
    predicates;

  foldr = f2: base: xs: if # xs is expected to be a list because builtins.head and builtins.tail are applied on it
    xs == []
    then base
    else f2
      (builtins.head xs)
      (builtins.tail xs |> foldr f2 base);

  foldr1 = f2: xs: xs
    |> (ys: if 
      ys == []
      then builtins.throw "foldr1 expects non-null lists"
      else ys)
    |> (zs: lib.list.foldr
      f2
      (builtins.head zs)
      (builtins.tail zs));

  last = xs: lib.list.foldr1
    (_: b: b)
    xs;
}

#+end_src

*** ./lib/path.nix

#+begin_src nix :tangle (org-entry-get nil "ITEM")

lib: {
  pathOnly = arg: if 
    builtins.isPath arg
    then arg
    else builtins.throw "this function is used strictly on paths";

  withPath = parentPath: baseStrs: builtins.map # parentPath should be a path
    (baseStr: (lib.path.pathOnly parentPath) + ("/" + s))
    baseStrs;

  pathToBasename = arg: arg
    |> lib.path.pathOnly
    |> builtins.toString
    |> (path: path 
      |> builtins.match ".*/(\\.*[^./]+)(\\.[^/]*)?" # builtins.match returns null if there's no match with the regex, or a list of capture groups
      |> builtins.head); 

  fileSearch = { # Maybe add recursion for directories (and symlinks pointing to directories) in the future
    root, # Search within root
    filetype, 
    suffix # Terminating substring
  }: let
    validFiletypes = [ # Based on the behaviour of builtins.readDir
      "directory"
      "regular" 
      "symlink"
      "unknown"
    ];

    entries = if 
      !(builtins.pathExists root) # Guard against non existent directories
      then builtins.throw ("there is no " + builtins.toString root + " directory in the filesystem")
      else if 
        !(lib.list.isMember filetype validFiletypes) # Guard against invalid filetypes
        then builtins.throw (
          "there is no '"
          + filetype 
          + "' filetype available, it should be one of: '"
          + builtins.concatStringsSep "', '" validFiletypes
          + "' (special filesystem entities like device files, named pipes/FIFOS, sockets)"
        )
        else builtins.readDir root; # The keys of the returned attribute set are relative path names (of type string) from root

  in entries
    |> builtins.attrNames
    |> builtins.filter (attrName: let 
      suffixLen = builtins.stringLength suffix;
    in 
      entries.${attrName} == filetype
      && builtins.substring
        (builtins.stringLength attrName - suffixLen)
        suffixLen
        attrName == suffix)
    |> builtins.map (attrName: let 
      tempath = root + "/${attrName}";
    in {
      basename = lib.path.pathToBasename tempath;
      path = tempath;
    });
}

#+end_src
