#+export_file_name: ./README.md

A tiny Nix library of auxiliary functions with no nixpkgs dependency (self-contained).

It may be used as a lightweight utility layer in Nix configurations, among other things.

* Laziness

The library uses a self-referencing attribute set instead of a recursive one, so modules can call each other while remaining independently importable. Due to Nix's laziness, nothing is evaluated until actually accessed.

The =./default.nix= file /* is the aggregator of the modules in =./lib= directory. Each module receives the whole =./lib= as a whole and can call siblings through it.

#+begin_src nix

let
  lib = {
    list = import ./lib/list.nix lib;
    path = import ./lib/path.nix lib;
  };
in
  lib

#+end_src

* Usage

** Warning

Some of the functions' definitions use the experimental pipe operators of Nix. Make sure you enable them via adding "pipe-operators" to the experimental-features list.

** Barebones import

Here is a minimal example of using the library as a standalone import:

#+begin_src nix

let 
  bibliothix = builtins.import 
    (builtins.fetchTarball {
      url = "https://github.com/multiades/bibliothix/archive/main.tar.gz";
    });
in 
  bibliothix.list.isMember "foo" [ "foo" "bar" ] # → true

#+end_src

** Flake input

For flake consumers (although the library is mostly static and this may be overkill): 

#+begin_src nix

{
  inputs.bibliothix.url = "github:multiades/bibliothix";

  # No `inputs` attribute

  outputs = { 
    bibliothix,
    ... 
  }: {
    # Usage
  };
}

#+end_src

* Reference

** =lib.list= module

=listOnly=, =isMember=, =cons=, =foldR=, =foldR1=, =last=.

** =lib.path= module

=pathOnly=, =pathToBasename=, =findFiles=.

*** ~findFiles : { root: Path, filetype: String, suffix: String } -> List~

Locates files in a directory matching a given filetype and a filename terminating substring. Returns a list of ={ basename, path }= attribute sets.

Valid filetypes (from =builtins.readDir=): =regular=, =directory=, =symlink=, =unknown=.

Note: the function is non-recursive, meaning it only searches the immediate contents of =root=.

Usage example on a directory named =./modules=:
#+begin_src nix

lib.path.findFiles {
  root = ./modules;
  filetype = "regular";
  suffix = ".nix"; # Or even "nix"
}

/*
 → [
     { 
       basename = "networking"; 
       path = /path/to/modules/networking.nix;
     }
     { 
       basename = "users";
       path = /path/to/modules/users.nix;
     }
   ]

#+end_src

Useful for auto-importing all desired files in a directory without manually listing them (it even handles files with multiple types, like =./foo.tar.gz=).

* License

AGPL-3.0-or-later. See [[LICENSE][LICENSE]].
